# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='doc',
            field=models.CharField(max_length=2048, null=True, verbose_name='doc'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='example',
            field=models.CharField(max_length=2048, null=True, verbose_name='e.g.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='note',
            field=models.CharField(max_length=2048, null=True, verbose_name='note'),
        ),
    ]
