# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_auto_20170721_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='doc',
            field=models.CharField(max_length=2048, null=True, verbose_name='文档'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='example',
            field=models.CharField(max_length=2048, null=True, verbose_name='示例'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='inTime',
            field=models.DateTimeField(auto_created=True, verbose_name='收录日期'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='intro',
            field=models.CharField(max_length=64, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(max_length=128, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='note',
            field=models.CharField(max_length=2048, null=True, verbose_name='笔记'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.Type', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='type',
            name='intro',
            field=models.CharField(max_length=16, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=16, verbose_name='分类名称'),
        ),
    ]
