# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_project_ploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='accept',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Accept'),
        ),
        migrations.AddField(
            model_name='headers',
            name='accept_encoding',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Accept-Encoding'),
        ),
        migrations.AddField(
            model_name='headers',
            name='accept_language',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Accept-Language'),
        ),
    ]
