# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_auto_20170807_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='extract',
            field=models.CharField(choices=[('extract_first', 'extract_first'), ('extract', 'extract')], default='extract_first', max_length=16, verbose_name='解析'),
        ),
    ]
