# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170703_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='edit_time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='level',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='remarks',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
