# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170822_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='in_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='In Time'),
            preserve_default=False,
        ),
    ]
