# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_in_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='in_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(auto_created=True, default=None, verbose_name='Create'),
        ),
    ]
