# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170822_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='问题')),
                ('in_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('re_time', models.DateTimeField(auto_now=True, verbose_name='解决时间')),
                ('state', models.BooleanField(default=False, verbose_name='状态')),
                ('answer', models.CharField(max_length=255, verbose_name='答案')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32, unique=True, verbose_name='word')),
                ('level', models.IntegerField(default=1, max_length=4, verbose_name='level')),
                ('hp', models.IntegerField(default=5, max_length=3, verbose_name='hp')),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create'),
        ),
    ]
