# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20170830_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='words',
            name='hp',
            field=models.IntegerField(default=5, verbose_name='hp'),
        ),
        migrations.AlterField(
            model_name='words',
            name='level',
            field=models.IntegerField(default=1, verbose_name='level'),
        ),
    ]
