# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Project Name')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128, verbose_name='URL path')),
                ('name', models.CharField(max_length=32, verbose_name='Pager Title')),
                ('state', models.BooleanField(default=False, verbose_name='Is parsed?')),
                ('in_date', models.DateTimeField(auto_now_add=True, verbose_name='In Date')),
                ('parse_date', models.DateTimeField(verbose_name='Parse Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.Project')),
            ],
        ),
    ]
