# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=1024, verbose_name='Item(JSON Date)')),
                ('inTime', models.DateTimeField(auto_now_add=True, verbose_name='In Time')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Project Name')),
                ('header', models.CharField(max_length=64, verbose_name='Data Header')),
                ('itemRules', models.CharField(max_length=255, verbose_name='Item Rules(JSON k-v)')),
                ('urlRules', models.CharField(max_length=255, verbose_name='URL Rules(JSON k-v)')),
                ('allowUrl', models.CharField(max_length=32, verbose_name='Allow URL')),
                ('allowed_domains', models.CharField(max_length=32, verbose_name='Allowed Domains')),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=64, verbose_name='URL link')),
                ('parsed', models.BooleanField(default=False, verbose_name='Is Parsed')),
                ('inTime', models.DateTimeField(auto_now_add=True, verbose_name='In Time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Project', verbose_name='Owner')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Project', verbose_name='Owner'),
        ),
    ]
