# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allowUrl',
            field=models.CharField(max_length=32, null=True, verbose_name='Allow URL'),
        ),
    ]
