# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20170625_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='header',
            new_name='columns',
        ),
        migrations.RemoveField(
            model_name='project',
            name='urlRules',
        ),
        migrations.AddField(
            model_name='project',
            name='nextPager',
            field=models.CharField(max_length=32, null=True, verbose_name='Next Pager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allowed_domains',
            field=models.CharField(max_length=32, null=True, verbose_name='Allowed Domains'),
        ),
    ]
