# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20170626_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=32, verbose_name='Column')),
                ('rule', models.CharField(max_length=32, verbose_name='Rule')),
                ('method', models.CharField(max_length=16, verbose_name='Parse method')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='itemRules',
        ),
        migrations.AddField(
            model_name='rules',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.Project', verbose_name='Project ID'),
        ),
    ]
