# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_auto_20170627_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='allowUrl',
            new_name='allow_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='nextPager',
            new_name='next_pager',
        ),
    ]
