# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_auto_20170627_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_rule',
            field=models.CharField(max_length=64, null=True, verbose_name='Link Rule'),
        ),
        migrations.AddField(
            model_name='rules',
            name='extract',
            field=models.CharField(default=None, max_length=16, verbose_name='Extract Method'),
            preserve_default=False,
        ),
    ]
