# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_auto_20170628_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='extract',
            field=models.CharField(default='extract_first', max_length=16, verbose_name='Extract Method'),
        ),
    ]
