# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_auto_20170628_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='link',
            field=models.CharField(max_length=128, verbose_name='URL link'),
        ),
    ]
