# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_auto_20170628_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='project',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='project',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
